"""M0 runtime backend: compile ``#@`` specs to icontract decorators.

Given a module's source and its parsed specs, emit a *checked copy* of the
module — the original file untouched, a ``<stem>_checked.py`` sibling where
each spec'd function carries ``@icontract.require`` / ``@icontract.ensure``
decorators (plus ``@icontract.snapshot`` for ``old(...)``). The checked module
is what CrossHair searches for counterexamples:

    crosshair check build/checked/foo_checked.py --analysis_kind icontract

``invariant`` and ``decreases`` clauses are recorded but not enforced at
runtime (they are inputs to the Dafny backend, M1).
"""

from __future__ import annotations

import ast

from ...frontend.parse import ModuleSpecs, rewrite_old

_IMPORTS = ("import copy", "import icontract")


def _indent_of(line: str) -> str:
    return line[: len(line) - len(line.lstrip())]


def _rewrite_old(expr: str) -> str:
    # AST-based: old(...) inside string literals stays literal text.
    return rewrite_old(expr, "OLD.{name}")


def _import_insertion_line(source: str) -> int:
    """First line our imports may occupy: after the module docstring and any
    ``from __future__`` imports (which must stay at the top of the file)."""
    module = ast.parse(source)
    line = 1
    body = module.body
    index = 0
    if (
        body
        and isinstance(body[0], ast.Expr)
        and isinstance(body[0].value, ast.Constant)
        and isinstance(body[0].value.value, str)
    ):
        line = (body[0].end_lineno or body[0].lineno) + 1
        index = 1
    while (
        index < len(body)
        and isinstance(body[index], ast.ImportFrom)
        and body[index].module == "__future__"
    ):
        line = (body[index].end_lineno or body[index].lineno) + 1
        index += 1
    return line


def emit_checked(source: str, specs: ModuleSpecs, src_name: str) -> str:
    if specs.errors:
        first = specs.errors[0]
        raise ValueError(
            f"cannot emit: spec error at line {first.line}: {first.error}"
        )
    lines = source.splitlines()
    insertions: dict[int, list[str]] = {}

    for fn in specs.functions:
        requires = fn.by_kind("requires")
        ensures = fn.by_kind("ensures")
        if not requires and not ensures:
            continue
        indent = _indent_of(lines[fn.anchor_lineno - 1])
        params = ", ".join(fn.params)
        req_args = params if params else ""
        ens_params = list(fn.params) + ["result"]
        old_names = sorted({n for c in ensures for n in c.old_names})
        if old_names:
            ens_params.append("OLD")
        ens_args = ", ".join(ens_params)

        decorators: list[str] = []
        for c in requires:
            decorators.append(
                f"{indent}@icontract.require(lambda {req_args}: {c.desugared}, "
                f"description={('requires ' + c.raw)!r})"
            )
        for name in old_names:
            decorators.append(
                f"{indent}@icontract.snapshot(lambda {name}: copy.deepcopy({name}), name={name!r})"
            )
        for c in ensures:
            decorators.append(
                f"{indent}@icontract.ensure(lambda {ens_args}: {_rewrite_old(c.desugared)}, "
                f"description={('ensures ' + c.raw)!r})"
            )
        insertions[fn.anchor_lineno] = decorators

    import_line = _import_insertion_line(source)
    out: list[str] = [f"# Generated by `lemmapy emit` -- DO NOT EDIT (source: {src_name})"]
    for lineno, line in enumerate(lines, start=1):
        if lineno == import_line:
            out.extend(_IMPORTS)
        if lineno in insertions:
            out.extend(insertions[lineno])
        out.append(line)
    if import_line == len(lines) + 1:
        out.extend(_IMPORTS)
    return "\n".join(out) + "\n"
